#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
mv constant/polyMesh constant/FLUID/.
runApplication `getApplication`
paraFoam -touchAll
#runApplication postProcess -func sampleDict

#------------------------------------------------------------------------------
